name: PigmanCore
version: '${project.version}'
main: fr.skytryx.pigmancore.PigmanCore
api-version: '1.20'
commands:
  stafftp:
    description: Command to stafftp (teleport whilst going into spectator mode)
    permission: survie.staff.stafftp
    usage: "§3Usage: /stafftp <player>"
  invsee:
    description: Command to see the inventory of a specific player
    permission: survie.staff.invsee
    usage: "§3Usage: /invsee <player>"
  lobby:
    description: Teleport to lobby
    usage: "§3Usage: /lobby"
    aliases: [ l, hub ]
  heal:
    description: heal you or someone
    permission: survie.staff.heal
    usage: "§3Usage: /heal <player>"
    aliases: [h]
  gamemode:
    description: change ton gamemode
    permission: survie.staff.gamemode
    usage: "§3Usage: /gamemode <0,1,2,3>"
    aliases: [ g, gm ]
  tp2p:
    description: Tp toi a un autre joueur
    permission: survie.staff.tp2p
    usage: "§3Usage: /tp2p <player>"
    aliases: [ tptop, tptoplayer ]
  tphere:
    description: Tp un autre joueur a toi
    permission: survie.staff.tphere
    usage: "§3Usage: /tp2p <player>"
    aliases: [ tph ]
  feed:
    description: Nourris toi ou un joueur joueur
    permission: survie.staff.feed
    usage: "§3Usage: /feed <player>"
    aliases: [ f ]
  ping :
    description: Recupere ton ping ou celui d'un autre joueur
    usage: "§3Usage: /ping <player>"